"""empty message

Revision ID: 51cb702aaea2
Revises: 5a206e553bfb
Create Date: 2024-04-24 15:34:57.383572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51cb702aaea2'
down_revision = '5a206e553bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pupil', schema=None) as batch_op:
        batch_op.alter_column('communication_pupil',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=8),
               existing_nullable=True)
        batch_op.alter_column('communication_tutor1',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=8),
               existing_nullable=True)
        batch_op.alter_column('communication_tutor2',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pupil', schema=None) as batch_op:
        batch_op.alter_column('communication_tutor2',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('communication_tutor1',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('communication_pupil',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
