"""empty message

Revision ID: 99fa5f4334a0
Revises: 51cb702aaea2
Create Date: 2024-05-12 23:23:25.738077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fa5f4334a0'
down_revision = '51cb702aaea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tutoring',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tutoring',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
